"""Generate a large equivalent source in Arc and Go, for compile-throughput timing.

Each generated function is small and independent, so the two files differ only in
syntax; the point is to compare front-end throughput on comparable input, not to
measure any particular optimisation.

    python gen_big.py 2000
"""
import sys

n = int(sys.argv[1]) if len(sys.argv) > 1 else 2000

arc = ["// Generated by gen_big.py - compile-throughput benchmark.", ""]
go = ["// Generated by gen_big.py - compile-throughput benchmark.", "package main", ""]

for i in range(n):
    arc.append(f"""fn f{i}(a: i32, b: i32) i32 {{
    let mut x: i32= a + b;
    let mut y: i32= a - b;
    let mut s: i32= 0;
    let mut k: i32= 0;
    while (k < 4) {{
        if (x > y) {{ s = s + x * {i % 7 + 1}; }} else {{ s = s - y; }}
        x = x + 1;
        k = k + 1;
    }}
    return s;
}}""")
    go.append(f"""func f{i}(a int32, b int32) int32 {{
	x := a + b
	y := a - b
	var s int32 = 0
	for k := 0; k < 4; k++ {{
		if x > y {{
			s = s + x*{i % 7 + 1}
		}} else {{
			s = s - y
		}}
		x = x + 1
	}}
	return s
}}""")

arc.append("pub fn main() i32 {")
arc.append("    let mut t: i32= 0;")
for i in range(0, n, max(1, n // 50)):
    arc.append(f"    t = t + f{i}(t, {i});")
arc.append("    return t & 1;")
arc.append("}")

go.append("func main() {")
go.append("\tvar t int32 = 0")
for i in range(0, n, max(1, n // 50)):
    go.append(f"\tt = t + f{i}(t, {i})")
go.append("\t_ = t")
go.append("}")

arc_text = "\n".join(arc) + "\n"
go_text = "\n".join(go) + "\n"
open("big.arc", "wb").write(arc_text.encode("utf-8"))
open("big.go", "wb").write(go_text.encode("utf-8"))
print("wrote big.arc (%d lines) and big.go (%d lines)"
      % (arc_text.count("\n"), go_text.count("\n")))
